name: Simple Start Up 
on:
  push:
    branches: [main]
jobs: 
  build:
    name: Build my virtual OS 
    runs-on: Ubuntu-22.04 
    steps:
      - name: Checkout private repo remotely
        uses: actions/checkout@v2.4.2
        with:
          repository: ICT-CET-Activities/hiddenRepo
          path: remote
          token: ${{secrets.TOKEN}}
      - name: Show hidden files 
        run: |
          cd remote 
          ls
          cat myText.txt
          cd ..
