name: Simple Start Up 
on:
  push:
    branches: [main]
jobs: 
  build:
    name: Build my virtual OS 
    runs-on: Ubuntu-22.04 
    steps:
      - name: Checkout private repo remotely
        uses: actions/checkout@v2
        with:
          repository: ICT-CET-Activities/hiddenRepo
          path: '/home/runner/work/SFA_RUN1_GIT/SFA_RUN1_GIT'
          token: ${{secrets.TOKEN}}
      - name: Show hidden files 
        run: |
          cd '/home/runner/work/SFA_RUN1_GIT/SFA_RUN1_GIT' ls
